# Generated by Django 3.2.7 on 2022-01-02 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('date_of_published', models.DateTimeField(default=datetime.datetime(2022, 1, 2, 13, 4, 58, 319653))),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'picture',
                'ordering': ['date_of_published'],
            },
        ),
        migrations.CreateModel(
            name='PictureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PH', 'photo'), ('VG', 'vectors_graphic'), ('IL', 'illustration')], max_length=100, unique=True)),
            ],
            options={
                'db_table': 'picture_category',
            },
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('extension', models.CharField(choices=[('JPEG', 'jpeg'), ('PNG', 'png'), ('SVG', 'svg')], max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture_info', to='picture.picture')),
            ],
            options={
                'db_table': 'picture_info',
            },
        ),
        migrations.AddConstraint(
            model_name='picturecategory',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['PH', 'VG', 'IL'])), name='picture_picturecategory_name_invalid'),
        ),
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='album_pictures', through='album.AlbumPicture', to='album.Album'),
        ),
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picture.picturecategory'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_picture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pictureinfo',
            constraint=models.CheckConstraint(check=models.Q(('extension__in', ['JPEG', 'PNG', 'SVG'])), name='picture_pictureinfo_extension_invalid'),
        ),
    ]
