# Generated by Django 3.2.7 on 2022-01-09 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.CharField(choices=[('PH', 'photo'), ('VG', 'vectors_graphic'), ('IL', 'illustration')], max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 19, 58, 57, 959102)),
        ),
    ]
