# Generated by Django 3.2.7 on 2021-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('picture', '0002_alter_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ManyToManyField(related_name='album_pictures', through='album.AlbumPicture', to='album.Album'),
        ),
    ]
