# Generated by Django 3.2.7 on 2022-01-09 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20220109_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 20, 13, 2, 457402)),
        ),
    ]
