# Generated by Django 3.2.7 on 2021-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('picture', '0003_picture_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='album_pictures', through='album.AlbumPicture', to='album.Album'),
        ),
    ]
