# Generated by Django 3.2.7 on 2022-01-15 13:57

import datetime
from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_alter_picture_date_of_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 16, 57, 15, 638518)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=picture.models.generate_upload_url),
        ),
    ]
