# Generated by Django 3.2.7 on 2022-01-16 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20220115_1657'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pictureinfo',
            name='picture_pictureinfo_extension_invalid',
        ),
        migrations.RemoveField(
            model_name='pictureinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pictureinfo',
            name='width',
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 12, 55, 14, 850736)),
        ),
        migrations.AlterField(
            model_name='pictureinfo',
            name='extension',
            field=models.CharField(max_length=100),
        ),
    ]
