# Generated by Django 3.2.7 on 2021-10-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_alter_picture_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
