# Generated by Django 3.2.7 on 2022-01-16 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_auto_20220116_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 13, 0, 58, 918308)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(unique=True, upload_to=picture.models.generate_upload_url),
        ),
        migrations.AlterField(
            model_name='pictureinfo',
            name='picture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture_info', to='picture.picture', to_field='image'),
        ),
    ]
