# Generated by Django 3.2.7 on 2021-10-10 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_auto_20211010_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='picture.picturecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 16, 52, 18, 375769)),
        ),
    ]
