# Generated by Django 3.2.7 on 2021-10-10 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0009_auto_20211010_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 16, 53, 51, 686359)),
        ),
    ]
