# Generated by Django 3.2.7 on 2021-10-10 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0020_auto_20211010_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 19, 0, 54, 955645)),
        ),
        migrations.AddConstraint(
            model_name='picturecategory',
            constraint=models.CheckConstraint(check=models.Q(('name__in', [('PH', 'photo'), ('VG', 'vectors_graphic'), ('IL', 'illustration')])), name='picture_picturecategory_name_invalid'),
        ),
    ]
