# Generated by Django 3.2.7 on 2021-10-10 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0022_alter_picture_date_of_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 19, 4, 50, 678928)),
        ),
        migrations.AlterField(
            model_name='picturecategory',
            name='name',
            field=models.CharField(choices=[('PH', 'photo'), ('VG', 'vectors_graphic'), ('IL', 'illustration')], max_length=100, unique=True),
        ),
    ]
