# Generated by Django 3.2.7 on 2021-10-10 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0023_auto_20211010_1904'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='picturecategory',
            name='picture_picturecategory_name_invalid',
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 19, 6, 7, 239826)),
        ),
        migrations.AddConstraint(
            model_name='picturecategory',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['PH', 'VG', 'IL'])), name='picture_picturecategory_name_invalid'),
        ),
    ]
