# Generated by Django 3.2.7 on 2021-10-10 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0025_auto_20211010_2101'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pictureinfo',
            name='picture_pictureinfo_extension_invalid',
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 21, 2, 32, 147634)),
        ),
        migrations.AddConstraint(
            model_name='pictureinfo',
            constraint=models.CheckConstraint(check=models.Q(('extension__in', ['JPEG', 'PNG', 'SVG'])), name='picture_pictureinfo_extension_invalid'),
        ),
    ]
