# Generated by Django 3.2.7 on 2021-10-10 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0026_auto_20211010_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 21, 2, 50, 632231)),
        ),
    ]
