# Generated by Django 3.2.7 on 2021-10-10 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0029_alter_picture_date_of_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 21, 4, 45, 304379)),
        ),
        migrations.DeleteModel(
            name='PictureInfo',
        ),
    ]
