# Generated by Django 3.2.7 on 2021-10-10 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0030_auto_20211010_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 21, 5, 33, 437139)),
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('extension', models.CharField(choices=[('JPEG', 'jpeg'), ('PNG', 'png'), ('SVG', 'svg')], max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
            options={
                'db_table': 'picture_info',
            },
        ),
        migrations.AddConstraint(
            model_name='pictureinfo',
            constraint=models.CheckConstraint(check=models.Q(('extension__in', ['JPEG', 'PNG', 'SVG'])), name='picture_pictureinfo_extension_invalid'),
        ),
    ]
