# Generated by Django 3.2.7 on 2021-10-11 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0031_auto_20211010_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-date_of_published']},
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 11, 57, 8, 233855)),
        ),
        migrations.AlterField(
            model_name='pictureinfo',
            name='picture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture_info', to='picture.picture'),
        ),
    ]
