# Generated by Django 3.2.7 on 2021-10-13 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_auto_20211013_2016'),
        ('picture', '0038_auto_20211013_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='album_pictures', through='album.AlbumPicture', to='album.Album'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 20, 16, 26, 159115)),
        ),
    ]
