# Generated by Django 3.2.7 on 2021-10-14 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0039_auto_20211013_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_of_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 21, 2, 879746)),
        ),
    ]
