# Generated by Django 3.2.7 on 2022-01-02 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 1, 2, 13, 4, 58, 318642))),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='AlbumPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_picture', to='album.album')),
            ],
            options={
                'db_table': 'album_picture',
            },
        ),
    ]
