# Generated by Django 3.2.7 on 2021-10-13 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20211012_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 53, 3, 744284)),
        ),
    ]
