# Generated by Django 3.2.7 on 2021-10-13 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0037_alter_picture_date_of_published'),
        ('album', '0004_auto_20211013_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 19, 37, 23, 802437)),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_picture', to='album.album'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture_album', to='picture.picture'),
        ),
    ]
