# Generated by Django 3.2.7 on 2021-10-13 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0037_alter_picture_date_of_published'),
        ('album', '0005_auto_20211013_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 20, 14, 58, 7345)),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mtm_album', to='album.album'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mtm_pictures', to='picture.picture'),
        ),
    ]
