# Generated by Django 3.2.7 on 2021-10-14 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0040_alter_picture_date_of_published'),
        ('album', '0007_auto_20211013_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 21, 2, 875456)),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_picture', to='album.album'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_album', to='picture.picture'),
        ),
    ]
